import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import swagger from '@fastify/swagger';
import scalar from '@scalar/fastify-api-reference';
import QRCode from 'qrcode';
import { z } from 'zod';
import { and, desc, eq, gt, inArray, isNotNull, isNull } from 'drizzle-orm';
import { customAlphabet } from 'nanoid';
import { db, pool } from '../db/client.js';
import { anonymousResponseLimits, questionOptions, questions, refreshTokens, surveyAnswers, surveyResponses, surveys, tenants, users } from '../db/schema.js';
import { env } from '../config/env.js';
import { anonymousFingerprint, createAccessToken, createRefreshJwt, hashPassword, hashToken, newRefreshToken, verifyPassword, verifyRefreshJwt } from '../lib/security.js';
import { fail, ok, type AuthedRequest } from './types.js';
import authPlugin from './plugins/auth.js';

const slug = customAlphabet('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', 16);
const registerSchema = z.object({ tenantName: z.string().min(2).max(160), name: z.string().min(2).max(160), email: z.string().email(), password: z.string().min(10).max(128) }).strict();
const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1) }).strict();
const surveySchema = z.object({ title: z.string().min(1).max(200), description: z.string().max(5000).optional(), startsAt: z.coerce.date().optional(), expiresAt: z.coerce.date().optional(), maxResponses: z.number().int().positive().optional() }).strict();
const questionSchema = z.object({ type: z.enum(['single_choice', 'multiple_choice', 'text']), title: z.string().min(1).max(500), description: z.string().max(5000).optional(), required: z.boolean().default(false), position: z.number().int().nonnegative(), options: z.array(z.object({ label: z.string().min(1).max(300), value: z.string().min(1).max(300), position: z.number().int().nonnegative() }).strict()).default([]) }).strict();
const responseSchema = z.object({ answers: z.array(z.object({ questionId: z.string().uuid(), textValue: z.string().max(10000).optional(), selectedOptionIds: z.array(z.string().uuid()).optional() }).strict()) }).strict();

function parse<T>(schema: z.ZodType<T>, body: unknown, reply: any): T | undefined { const result = schema.safeParse(body); if (!result.success) { reply.code(422).send(fail('VALIDATION_ERROR', 'The request is invalid', result.error.issues)); return; } return result.data; }
function auth(app: any, request: AuthedRequest, reply: any) { return app.authenticate(request, reply); }
function access(request: AuthedRequest) { if (!request.auth) throw new Error('auth'); return request.auth; }
function resourceError(reply: any, message = 'Resource not found') { return reply.code(404).send(fail('NOT_FOUND', message)); }

export function buildApp() {
  const app = Fastify({ logger: { level: env.NODE_ENV === 'production' ? 'info' : 'warn' }, bodyLimit: 1024 * 1024 });
  app.register(cors, { origin: env.CORS_ORIGIN.split(',').map((x) => x.trim()) });
  app.register(helmet);
  app.register(rateLimit, { global: false, max: 100, timeWindow: '1 minute' });
  app.register(swagger, { openapi: { info: { title: 'Anonymous Survey API', version: '1.0.0' }, servers: [{ url: env.API_URL }], components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } } }, tags: [{ name: 'health' }, { name: 'auth' }, { name: 'surveys' }, { name: 'public' }] } });
  app.register(authPlugin);
  app.get('/health', { schema: { tags: ['health'] } }, async () => ({ data: { status: 200, code: 'HELTING TEST OK', message: 'API ON' } }));
  app.get('/docs/json', async () => app.swagger());
  app.register(async (v1) => {
    v1.get('/health', async () => ({ data: { status: 200, code: 'HELTING TEST OK', message: 'API ON' } }));
    v1.post('/auth/register', { config: { rateLimit: { max: env.RATE_LIMIT_LOGIN_MAX, timeWindow: env.RATE_LIMIT_LOGIN_WINDOW } } }, async (request, reply) => {
      const input = parse(registerSchema, request.body, reply); if (!input) return;
      const email = input.email.toLowerCase();
      const existing = await db.select({ id: users.id }).from(users).where(eq(users.email, email)).limit(1); if (existing.length) return reply.code(409).send(fail('CONFLICT', 'Email already registered'));
      const [tenant] = await db.insert(tenants).values({ name: input.tenantName, contactEmail: email }).returning();
      const [user] = await db.insert(users).values({ tenantId: tenant.id, name: input.name, email, passwordHash: await hashPassword(input.password), role: 'owner' }).returning({ id: users.id, tenantId: users.tenantId, name: users.name, email: users.email, role: users.role });
      return reply.code(201).send(ok({ user, tenant }));
    });
    v1.post('/auth/login', { config: { rateLimit: { max: env.RATE_LIMIT_LOGIN_MAX, timeWindow: env.RATE_LIMIT_LOGIN_WINDOW } } }, async (request, reply) => {
      const input = parse(loginSchema, request.body, reply); if (!input) return; const found = await db.select().from(users).where(and(eq(users.email, input.email.toLowerCase()), isNull(users.deletedAt))).limit(1); const user = found[0];
      if (!user || !user.active || !(await verifyPassword(user.passwordHash, input.password))) return reply.code(401).send(fail('UNAUTHORIZED', 'Invalid credentials'));
      const refresh = newRefreshToken(); const [session] = await db.insert(refreshTokens).values({ tenantId: user.tenantId, userId: user.id, tokenHash: hashToken(refresh), expiresAt: new Date(Date.now() + 30 * 86400000) }).returning({ id: refreshTokens.id });
      return ok({ accessToken: await createAccessToken({ sub: user.id, tenantId: user.tenantId, role: user.role }), refreshToken: await createRefreshJwt({ sub: user.id, tenantId: user.tenantId, role: user.role, jti: session.id }), tokenType: 'Bearer' });
    });
    v1.post('/auth/refresh', { config: { rateLimit: { max: env.RATE_LIMIT_REFRESH_MAX, timeWindow: env.RATE_LIMIT_REFRESH_WINDOW } } }, async (request, reply) => {
      const body = z.object({ refreshToken: z.string().min(1) }).safeParse(request.body); if (!body.success) return reply.code(422).send(fail('VALIDATION_ERROR', 'The request is invalid', body.error.issues));
      try { const claims = await verifyRefreshJwt(body.data.refreshToken); const current = (await db.select().from(refreshTokens).where(and(eq(refreshTokens.id, claims.jti), eq(refreshTokens.tokenHash, hashToken(body.data.refreshToken)), isNull(refreshTokens.revokedAt))).limit(1))[0]; if (!current || current.expiresAt < new Date()) throw new Error('revoked');
        const nextRaw = newRefreshToken(); const [next] = await db.insert(refreshTokens).values({ tenantId: current.tenantId, userId: current.userId, tokenHash: hashToken(nextRaw), expiresAt: new Date(Date.now() + 30 * 86400000) }).returning({ id: refreshTokens.id }); await db.update(refreshTokens).set({ revokedAt: new Date(), replacedById: next.id }).where(eq(refreshTokens.id, current.id));
        return ok({ accessToken: await createAccessToken({ sub: claims.sub, tenantId: claims.tenantId, role: claims.role }), refreshToken: await createRefreshJwt({ sub: claims.sub, tenantId: claims.tenantId, role: claims.role, jti: next.id }), tokenType: 'Bearer' });
      } catch { return reply.code(401).send(fail('UNAUTHORIZED', 'Invalid or revoked refresh token')); }
    });
    v1.post('/auth/logout', { preHandler: (request, reply) => auth(app, request as AuthedRequest, reply) }, async (request, reply) => { const body = z.object({ refreshToken: z.string() }).safeParse(request.body); if (body.success) await db.update(refreshTokens).set({ revokedAt: new Date() }).where(eq(refreshTokens.tokenHash, hashToken(body.data.refreshToken))); return reply.code(204).send(); });
    v1.get('/auth/me', { preHandler: (request, reply) => auth(app, request as AuthedRequest, reply) }, async (request, reply) => { const a = access(request as AuthedRequest); const user = (await db.select({ id: users.id, tenantId: users.tenantId, name: users.name, email: users.email, role: users.role }).from(users).where(and(eq(users.id, a.sub), eq(users.tenantId, a.tenantId), isNull(users.deletedAt))).limit(1))[0]; return user ? ok(user) : resourceError(reply); });
    v1.addHook('preHandler', async (request, reply) => { if (request.url.startsWith('/public/')) return; });
    const protectedPre = (request: any, reply: any) => auth(app, request, reply);
    v1.get('/tenants/me', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const tenant = (await db.select().from(tenants).where(and(eq(tenants.id, a.tenantId), isNull(tenants.deletedAt))).limit(1))[0]; return tenant ? ok(tenant) : resourceError(reply); });
    v1.patch('/tenants/me', { preHandler: [protectedPre, (request: any, reply: any) => (app as any).requireRole(['owner', 'admin'])(request, reply)] }, async (request, reply) => { const a = access(request as AuthedRequest); const input = parse(z.object({ name: z.string().min(2).max(160).optional(), publicName: z.string().max(160).optional(), contactEmail: z.string().email().optional(), timezone: z.string().max(80).optional(), settings: z.record(z.string(), z.unknown()).optional() }).strict(), request.body, reply); if (!input) return; const tenant = (await db.update(tenants).set({ ...input, updatedAt: new Date() }).where(eq(tenants.id, a.tenantId)).returning())[0]; return ok(tenant); });

    v1.post('/users', { preHandler: [protectedPre, (request: any, reply: any) => (app as any).requireRole(['owner', 'admin'])(request, reply)] }, async (request, reply) => { const a = access(request as AuthedRequest); const input = parse(z.object({ name: z.string().min(2).max(160), email: z.string().email(), password: z.string().min(10), role: z.enum(['admin', 'member']).default('member') }).strict(), request.body, reply); if (!input) return; const [user] = await db.insert(users).values({ tenantId: a.tenantId, name: input.name, email: input.email.toLowerCase(), passwordHash: await hashPassword(input.password), role: input.role }).returning({ id: users.id, tenantId: users.tenantId, name: users.name, email: users.email, role: users.role, active: users.active }); return reply.code(201).send(ok(user)); });
    v1.get('/users', { preHandler: protectedPre }, async (request) => { const a = access(request as AuthedRequest); return ok(await db.select({ id: users.id, tenantId: users.tenantId, name: users.name, email: users.email, role: users.role, active: users.active, createdAt: users.createdAt }).from(users).where(and(eq(users.tenantId, a.tenantId), isNull(users.deletedAt)))); });
    v1.get('/users/me', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const user = (await db.select({ id: users.id, tenantId: users.tenantId, name: users.name, email: users.email, role: users.role, active: users.active }).from(users).where(and(eq(users.id, a.sub), eq(users.tenantId, a.tenantId), isNull(users.deletedAt))).limit(1))[0]; return user ? ok(user) : resourceError(reply); });
    v1.patch('/users/me', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const input = parse(z.object({ name: z.string().min(2).max(160).optional(), password: z.string().min(10).optional() }).strict(), request.body, reply); if (!input) return; const [user] = await db.update(users).set({ name: input.name, passwordHash: input.password ? await hashPassword(input.password) : undefined, updatedAt: new Date() }).where(and(eq(users.id, a.sub), eq(users.tenantId, a.tenantId), isNull(users.deletedAt))).returning({ id: users.id, name: users.name, email: users.email }); return user ? ok(user) : resourceError(reply); });
    v1.delete('/users/:id', { preHandler: [protectedPre, (request: any, reply: any) => (app as any).requireRole(['owner', 'admin'])(request, reply)] }, async (request, reply) => { const a = access(request as AuthedRequest); await db.update(users).set({ deletedAt: new Date(), active: false, updatedAt: new Date() }).where(and(eq(users.id, (request.params as any).id), eq(users.tenantId, a.tenantId))); await db.update(refreshTokens).set({ revokedAt: new Date() }).where(and(eq(refreshTokens.userId, (request.params as any).id), eq(refreshTokens.tenantId, a.tenantId))); return reply.code(204).send(); });
    v1.post('/users/me/delete', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); await db.update(users).set({ deletedAt: new Date(), active: false, updatedAt: new Date() }).where(and(eq(users.id, a.sub), eq(users.tenantId, a.tenantId))); await db.update(refreshTokens).set({ revokedAt: new Date() }).where(and(eq(refreshTokens.userId, a.sub), eq(refreshTokens.tenantId, a.tenantId))); return reply.code(204).send(); });
    v1.post('/users/me/restore', async (request, reply) => { const body = z.object({ email: z.string().email(), password: z.string() }).safeParse(request.body); if (!body.success) return reply.code(422).send(fail('VALIDATION_ERROR', 'The request is invalid', body.error.issues)); const user = (await db.select().from(users).where(and(eq(users.email, body.data.email.toLowerCase()), isNotNull(users.deletedAt))).limit(1))[0]; if (!user || !user.deletedAt || Date.now() - user.deletedAt.getTime() > 30 * 86400000 || !(await verifyPassword(user.passwordHash, body.data.password))) return reply.code(404).send(fail('NOT_FOUND', 'Account cannot be restored')); const [restored] = await db.update(users).set({ deletedAt: null, active: true, updatedAt: new Date() }).where(eq(users.id, user.id)).returning({ id: users.id, email: users.email, active: users.active }); return ok(restored); });

    v1.post('/surveys', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const input = parse(surveySchema, request.body, reply); if (!input) return; const survey = (await db.insert(surveys).values({ ...input, tenantId: a.tenantId, publicSlug: slug() }).returning())[0]; return reply.code(201).send(ok(survey)); });
    v1.get('/surveys', { preHandler: protectedPre }, async (request) => { const a = access(request as AuthedRequest); return ok(await db.select().from(surveys).where(and(eq(surveys.tenantId, a.tenantId), isNull(surveys.deletedAt))).orderBy(desc(surveys.createdAt))); });
    v1.get('/surveys/:id', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const id = (request.params as { id: string }).id; const survey = (await db.select().from(surveys).where(and(eq(surveys.id, id), eq(surveys.tenantId, a.tenantId), isNull(surveys.deletedAt))).limit(1))[0]; return survey ? ok(survey) : resourceError(reply); });
    v1.patch('/surveys/:id', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const input = parse(surveySchema.partial(), request.body, reply); if (!input) return; const survey = (await db.update(surveys).set({ ...input, updatedAt: new Date() }).where(and(eq(surveys.id, (request.params as any).id), eq(surveys.tenantId, a.tenantId), isNull(surveys.deletedAt))).returning())[0]; return survey ? ok(survey) : resourceError(reply); });
    v1.delete('/surveys/:id', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); await db.update(surveys).set({ deletedAt: new Date(), updatedAt: new Date() }).where(and(eq(surveys.id, (request.params as any).id), eq(surveys.tenantId, a.tenantId))); return reply.code(204).send(); });
    v1.post('/surveys/:id/publish', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const survey = (await db.update(surveys).set({ status: 'published', publishedAt: new Date(), updatedAt: new Date() }).where(and(eq(surveys.id, (request.params as any).id), eq(surveys.tenantId, a.tenantId), isNull(surveys.deletedAt))).returning())[0]; return survey ? ok(survey) : resourceError(reply); });
    v1.post('/surveys/:id/close', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const survey = (await db.update(surveys).set({ status: 'closed', closedAt: new Date(), updatedAt: new Date() }).where(and(eq(surveys.id, (request.params as any).id), eq(surveys.tenantId, a.tenantId), isNull(surveys.deletedAt))).returning())[0]; return survey ? ok(survey) : resourceError(reply); });
    v1.post('/surveys/:surveyId/questions', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const input = parse(questionSchema, request.body, reply); if (!input) return; const survey = (await db.select({ id: surveys.id }).from(surveys).where(and(eq(surveys.id, (request.params as any).surveyId), eq(surveys.tenantId, a.tenantId), isNull(surveys.deletedAt))).limit(1))[0]; if (!survey) return resourceError(reply); const question = (await db.insert(questions).values({ surveyId: survey.id, ...input }).returning())[0]; if (input.options.length) await db.insert(questionOptions).values(input.options.map((o) => ({ ...o, questionId: question.id }))); return reply.code(201).send(ok(question)); });
    v1.get('/surveys/:surveyId/questions', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const survey = (await db.select({ id: surveys.id }).from(surveys).where(and(eq(surveys.id, (request.params as any).surveyId), eq(surveys.tenantId, a.tenantId))).limit(1))[0]; if (!survey) return resourceError(reply); return ok(await db.select().from(questions).where(and(eq(questions.surveyId, survey.id), isNull(questions.deletedAt))).orderBy(questions.position)); });
    v1.patch('/surveys/:surveyId/questions/:questionId', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const input = parse(questionSchema.partial(), request.body, reply); if (!input) return; const survey = (await db.select({ id: surveys.id }).from(surveys).where(and(eq(surveys.id, (request.params as any).surveyId), eq(surveys.tenantId, a.tenantId))).limit(1))[0]; if (!survey) return resourceError(reply); const { options: _options, ...questionInput } = input; const [question] = await db.update(questions).set({ ...questionInput, updatedAt: new Date() }).where(and(eq(questions.id, (request.params as any).questionId), eq(questions.surveyId, survey.id), isNull(questions.deletedAt))).returning(); return question ? ok(question) : resourceError(reply); });
    v1.delete('/surveys/:surveyId/questions/:questionId', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const survey = (await db.select({ id: surveys.id }).from(surveys).where(and(eq(surveys.id, (request.params as any).surveyId), eq(surveys.tenantId, a.tenantId))).limit(1))[0]; if (!survey) return resourceError(reply); await db.update(questions).set({ deletedAt: new Date(), updatedAt: new Date() }).where(and(eq(questions.id, (request.params as any).questionId), eq(questions.surveyId, survey.id))); return reply.code(204).send(); });
    v1.patch('/surveys/:surveyId/questions/reorder', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const input = parse(z.object({ questionIds: z.array(z.string().uuid()).min(1) }).strict(), request.body, reply); if (!input) return; const survey = (await db.select({ id: surveys.id }).from(surveys).where(and(eq(surveys.id, (request.params as any).surveyId), eq(surveys.tenantId, a.tenantId))).limit(1))[0]; if (!survey) return resourceError(reply); await db.transaction(async (tx) => { for (const [position, id] of input.questionIds.entries()) await tx.update(questions).set({ position, updatedAt: new Date() }).where(and(eq(questions.id, id), eq(questions.surveyId, survey.id))); }); return ok({ reordered: true }); });
    v1.get('/surveys/:id/qrcode', { preHandler: protectedPre }, async (request, reply) => { const a = access(request as AuthedRequest); const survey = (await db.select({ publicSlug: surveys.publicSlug }).from(surveys).where(and(eq(surveys.id, (request.params as any).id), eq(surveys.tenantId, a.tenantId))).limit(1))[0]; if (!survey) return resourceError(reply); return ok({ publicSlug: survey.publicSlug, dataUrl: await QRCode.toDataURL(`${env.PUBLIC_APP_URL}/survey/${survey.publicSlug}`) }); });
    v1.delete('/users/me', async (_r, reply) => reply.code(404).send(fail('NOT_FOUND', 'Use /v1/users/me/delete')));

    v1.get('/public/surveys/:publicSlug', async (request, reply) => { const survey = (await db.select({ id: surveys.id, title: surveys.title, description: surveys.description, publicSlug: surveys.publicSlug, status: surveys.status }).from(surveys).where(and(eq(surveys.publicSlug, (request.params as any).publicSlug), eq(surveys.status, 'published'), isNull(surveys.deletedAt))).limit(1))[0]; if (!survey) return reply.code(404).send(fail('NOT_FOUND', 'Published survey not found')); const qs = await db.select().from(questions).where(and(eq(questions.surveyId, survey.id), isNull(questions.deletedAt))).orderBy(questions.position); return ok({ ...survey, questions: qs }); });
    v1.post('/public/surveys/:publicSlug/responses', async (request, reply) => { const input = parse(responseSchema, request.body, reply); if (!input) return; const survey = (await db.select().from(surveys).where(and(eq(surveys.publicSlug, (request.params as any).publicSlug), eq(surveys.status, 'published'), isNull(surveys.deletedAt))).limit(1))[0]; if (!survey) return reply.code(404).send(fail('SURVEY_NOT_PUBLISHED', 'Survey is not available')); const qs = await db.select().from(questions).where(and(eq(questions.surveyId, survey.id), isNull(questions.deletedAt))); const validIds = new Set(qs.map((q) => q.id)); if (input.answers.some((a) => !validIds.has(a.questionId)) || qs.some((q) => q.required && !input.answers.some((a) => a.questionId === q.id && (a.textValue?.trim() || a.selectedOptionIds?.length)))) return reply.code(422).send(fail('VALIDATION_ERROR', 'Answers do not match survey questions')); const window = Math.floor(Date.now() / (env.ANONYMOUS_RESPONSE_WINDOW_HOURS * 3600000)); const fingerprint = anonymousFingerprint(survey.publicSlug, request.ip, String(request.headers['user-agent'] ?? ''), window); const existing = await db.select().from(anonymousResponseLimits).where(and(eq(anonymousResponseLimits.surveyId, survey.id), eq(anonymousResponseLimits.fingerprint, fingerprint), gt(anonymousResponseLimits.expiresAt, new Date()))).limit(1); if (existing.length) return reply.code(409).send(fail('SURVEY_ALREADY_ANSWERED', 'This technical origin has already answered within the retention window')); const response = (await db.insert(surveyResponses).values({ surveyId: survey.id }).returning())[0]; if (input.answers.length) await db.insert(surveyAnswers).values(input.answers.map((a) => ({ responseId: response.id, questionId: a.questionId, textValue: a.textValue, selectedOptionIds: a.selectedOptionIds }))); await db.insert(anonymousResponseLimits).values({ surveyId: survey.id, fingerprint, expiresAt: new Date(Date.now() + env.ANONYMOUS_RESPONSE_WINDOW_HOURS * 3600000) }); return reply.code(201).send(ok({ submitted: true })); });
  }, { prefix: '/v1' });
  app.setErrorHandler((error: any, request, reply) => { request.log.error(error); const status = error.statusCode && error.statusCode >= 400 ? error.statusCode : 500; return reply.code(status).send(fail(status === 500 ? 'INTERNAL_SERVER_ERROR' : 'REQUEST_ERROR', env.NODE_ENV === 'production' && status === 500 ? 'Internal server error' : error.message)); });
  app.register(scalar, { routePrefix: '/docs', configuration: { url: '/docs/json', pageTitle: 'Anonymous Survey API' } });
  app.addHook('onClose', async () => { await pool.end(); });
  return app;
}
