/**
 * Sincronizador Bun: coleta as últimas versões das fontes oficiais DATASUS e cria GitHub Releases públicas.
 * Não executa os arquivos obtidos; apenas transfere os binários oficiais e atualiza o manifesto do catálogo.
 */
type ProgramId = "SISAIH01" | "BPA" | "SIA";
type Candidate = { id: string; program: ProgramId; programName: string; version: string; filename: string; size: string; sourceUrl: string; sourcePage: string; publishedLabel: string; competence?: string; tag: string; title: string; };
type PublishedItem = Candidate & { downloadUrl: string; delivery: "github-release" | "official-source"; };
const REPOSITORY = process.env.GITHUB_REPOSITORY ?? "BRConnect/datasus-releases";
const SIH_URL = "http://sihd.datasus.gov.br/versao/versao_sisaih01.php";
const BPA_URL = "https://sia.datasus.gov.br/versao/listar_ftp_bpa.php";
const SIA_URL = "https://sia.datasus.gov.br/versao/listar_ftp_sia.php";
const decode = (value: string) => value.replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&#0?39;/g, "'").replace(/&quot;/g, '"').replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
async function getHtml(url: string) { const response = await fetch(url, { headers: { "user-agent": "datasus-releases-sync/1.0" } }); if (!response.ok) throw new Error(`Falha ao consultar ${url}: HTTP ${response.status}`); return response.text(); }
function parseSih(html: string): Candidate[] {
  const competenceMatch = /CMPT\s+(\d{2}\/\d{4})/i.exec(html); if (!competenceMatch) throw new Error("Competência atual do SISAIH01 não encontrada.");
  const start = competenceMatch.index; const nextCompetence = html.slice(start + competenceMatch[0].length).search(/CMPT\s+\d{2}\/\d{4}/i); const section = html.slice(start, nextCompetence === -1 ? undefined : start + competenceMatch[0].length + nextCompetence);
  const links = [...section.matchAll(/href=["']([^"']+sisaih01_ver(\d+)\.exe)["'][^>]*>([^<]+)</gi)]; if (!links.length) throw new Error("Instaladores atuais do SISAIH01 não encontrados.");
  const competence = competenceMatch[1]; const versions = links.map((match) => { const digits = match[2]; return { filename: decode(match[3]), version: `${digits.slice(0, 2)}.${digits.slice(2)}`, sourceUrl: match[1].replace(/\s/g, "") }; }); const versionToken = versions.map((item) => item.version.replace(".", "-")).join("-");
  return versions.map((item) => ({ id: `sisaih01-${item.version.replace(".", "-")}`, program: "SISAIH01", programName: "Sistema de Informações Hospitalares", version: item.version, filename: item.filename, size: "Conforme arquivo oficial", sourceUrl: item.sourceUrl, sourcePage: SIH_URL, publishedLabel: `Competência ${competence}`, competence, tag: `sih-sisaih01-${competence.replace("/", "-")}-v${versionToken}`, title: `SISAIH01 · competência ${competence} · versões ${versions.map((entry) => entry.version).join(" e ")}` }));
}
function tableEntry(html: string, filename: string) { const escapedName = filename.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); const expression = new RegExp(`href=["']([^"']+)["'][^>]*>${escapedName}<\\/a><\\/td>\\s*<td[^>]*>([\\s\\S]*?)<\\/td>\\s*<td[^>]*>([\\s\\S]*?)<\\/td>`, "i"); const match = expression.exec(html); if (!match) throw new Error(`Metadados de ${filename} não encontrados.`); return { sourceUrl: decode(match[1]), date: decode(match[2]), size: decode(match[3]) }; }
function parseBpa(html: string): Candidate { const filename = [...html.matchAll(/>(BPAMAG\d+\.exe)</gi)].at(-1)?.[1]; if (!filename) throw new Error("Instalador BPA não encontrado."); const entry = tableEntry(html, filename); const numericVersion = /^BPAMAG(\d{2})(\d{2})\.exe$/i.exec(filename); const version = numericVersion ? `${numericVersion[1]}.${numericVersion[2]}` : filename; return { id: `bpa-${version.replace(".", "-")}`, program: "BPA", programName: "Boletim de Produção Ambulatorial", version, filename, size: entry.size, sourceUrl: entry.sourceUrl, sourcePage: BPA_URL, publishedLabel: entry.date, tag: `bpa-v${version.replace(".", "-")}`, title: `BPA · versão ${version}` }; }
function parseSia(html: string): Candidate { const candidates = [...html.matchAll(/>(BDSIA(\d{4})(\d{2})([a-z])\.exe)</gi)].map((match) => ({ filename: match[1], year: match[2], month: match[3], suffix: match[4] })).sort((left, right) => right.filename.localeCompare(left.filename)); const latest = candidates[0]; if (!latest) throw new Error("Banco de dados mensal SIA não encontrado."); const entry = tableEntry(html, latest.filename); const version = `${latest.year}.${latest.month}${latest.suffix}`; return { id: `sia-${latest.year}${latest.month}${latest.suffix}`, program: "SIA", programName: "Banco de Dados do SIA", version, filename: latest.filename, size: entry.size, sourceUrl: entry.sourceUrl, sourcePage: SIA_URL, publishedLabel: entry.date, tag: `sia-bd-${latest.year}${latest.month}${latest.suffix}`, title: `SIA · banco mensal ${version}` }; }
async function run(command: string[], quiet = false) { const spawned = Bun.spawn(command, { stdout: quiet ? "pipe" : "inherit", stderr: "inherit", env: process.env }); const exitCode = await spawned.exited; if (exitCode !== 0) throw new Error(`Comando falhou (${exitCode}): ${command.join(" ")}`); return quiet ? (await new Response(spawned.stdout).text()).trim() : ""; }
async function releaseExists(tag: string) { const spawned = Bun.spawn(["gh", "release", "view", tag, "--repo", REPOSITORY], { stdout: "ignore", stderr: "ignore", env: process.env }); return (await spawned.exited) === 0; }
async function publish(candidate: Candidate): Promise<PublishedItem> { const releaseUrl = `https://github.com/${REPOSITORY}/releases/download/${candidate.tag}/${candidate.filename}`; if (await releaseExists(candidate.tag)) { console.log(`Release já existe: ${candidate.tag}`); return { ...candidate, downloadUrl: releaseUrl, delivery: "github-release" }; } const workDir = (await Bun.$`mktemp -d`.text()).trim(); const destination = `${workDir}/${candidate.filename}`; try { console.log(`Baixando ${candidate.filename} da fonte oficial...`); await run(["curl", "--fail", "--location", "--show-error", "--retry", "3", "--retry-all-errors", "--connect-timeout", "30", "--max-time", "1200", "--ftp-pasv", "--output", destination, candidate.sourceUrl]); if (!(await Bun.file(destination).exists())) throw new Error(`Download ausente: ${candidate.filename}`); await run(["gh", "release", "create", candidate.tag, destination, "--repo", REPOSITORY, "--title", candidate.title, "--notes", `Arquivo obtido automaticamente da fonte oficial DATASUS.\n\nOrigem: ${candidate.sourcePage}\nArquivo: ${candidate.filename}`, "--latest=false"]); return { ...candidate, downloadUrl: releaseUrl, delivery: "github-release" }; } finally { await run(["rm", "-rf", workDir]); } }
async function main() { console.log("Consultando páginas oficiais DATASUS..."); const [sihHtml, bpaHtml, siaHtml] = await Promise.all([getHtml(SIH_URL), getHtml(BPA_URL), getHtml(SIA_URL)]); const candidates = [...parseSih(sihHtml), parseBpa(bpaHtml), parseSia(siaHtml)]; console.log(`Encontrados ${candidates.length} arquivo(s) atuais.`); const releases: PublishedItem[] = []; for (const candidate of candidates) releases.push(await publish(candidate)); const manifest = { generatedAt: new Date().toISOString(), repository: REPOSITORY, releases: releases.map(({ tag: _tag, title: _title, ...item }) => item) }; await Bun.write("public/releases.json", `${JSON.stringify(manifest, null, 2)}\n`); console.log("Manifesto público atualizado."); }
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exit(1); });
